- src/commands/moderation/Kick.ts
- src/commands/moderation/Warn.ts
- src/commands/moderation/bans/Ban.ts
- src/commands/moderation/bans/Unban.ts
- src/commands/moderation/timeout/Timeout.ts
- src/commands/moderation/timeout/Untimeout.ts
• Paraphrased the Moderation responses and turned their Ephemeral to False
• Removed Inline from the Behaviour/Warn Log Embed
> Updation of Moderation Command Reponses and Behaviour/Warn Log Embeds

- src/commands/miscellaneous/StudyChannel.ts
Displays all study channels with their helper and study ping roles, ephemerally
> Add /study_channel list

- src/commands/study/pyp/RandomPyp.ts
- QP link
- MS link
- Ephemeral except in VCs
> Update RandomPyp.ts to the old format

- src/commands/menus/Helper.ts
Replaced `interaction.channel.send` with `interaction.reply`
> Fix helper ping showing "did not respond"

- src/commands/menus/Pin.ts
- src/commands/menus/Unpin.ts
- src/commands/miscellaneous/GoStudy.ts
- src/commands/moderation/Kick.ts
- src/commands/moderation/bans/Ban.ts
- src/commands/moderation/bans/Unban.ts
- src/commands/moderation/roles/ColorRoles.ts
- src/commands/moderation/roles/ReactionRoles.ts
- src/commands/moderation/timeout/Timeout.ts
- src/commands/moderation/timeout/Untimeout.ts
- src/commands/study/pyp/PypSearch.ts
- src/events/MessageCreate.ts
- src/registry/DiscordClient.ts
Changed 12 files to a new error log format.
changed the DiscordClient.ts file to fit the new format
> Updating error log format

- src/events/MessageCreate.ts
Interaction.  doesn't work here, changed to message.
> Fixed a mistake in the error log

- src/commands/miscellaneous/RemoveGoStudy.ts
Fixed error log, it was still using the old error logging and I changed it to the new
> Fixed error logs in removegostudy

- src/commands/moderation/History.ts
Using 12-hour format, local time
Requested by xxspidey
> Add time stamps to /history

- src/data.ts
added a lot more aliases with other languages including hindi, urdu, arabic, french, german, malay, and mandarin chinese
> Update ty/yw aliases to include more languages

- src/events/MessageCreate.ts
_Made the bot a li'l ruder_
\+ Updated the "np" bot message
> Stop pinging me!

- src/events/MessageCreate.ts
Reverts Sachin-dot-py/r-igcse-bot#84
> Revert "Stop pinging me!"

- src/events/MessageCreate.ts
Was accidentally reverted before at #85, so fixed again
> Fixed "np" at bot messages

- src/commands/moderation/Slowmode.ts
Added `/slowmode time` with an optional `channel` option to add a slowmode
> feat: /slowmode: added command to add/remove slowmode

- src/events/AutoModerationActionExecution.ts
Removed author from timeouts by automod
> fix: remove author from timeouts by automod

- src/commands/menus/StickyPin.ts
- src/commands/menus/TogglePin.ts
- Auto-shifts oldest pins upon hitting pin limit
- Prompts to shift to old pins when unpinning
- Also works with sticky pins
> Old Pins: Threads in every channel to store the oldest pins

- src/commands/study/Resources.ts
Bypass discord's limit using multiple rows of links
> Fix /resources for >5 links

- src/commands/HOTM/Vote.ts
- src/commands/menus/Helper.ts
- src/commands/miscellaneous/GoStudy.ts
- src/commands/moderation/History.ts
- src/commands/moderation/Kick.ts
- src/commands/moderation/RemoveInfraction.ts
- src/commands/moderation/SetReputation.ts
- src/commands/moderation/Warn.ts
- src/commands/moderation/bans/Ban.ts
- src/commands/moderation/bans/Unban.ts
- src/commands/moderation/message/Message.ts
- src/commands/moderation/timeout/Timeout.ts
- src/commands/moderation/timeout/Untimeout.ts
- src/events/AutoModerationActionExecution.ts
- src/events/GuildBanAdd.ts
- src/events/GuildBanRemove.ts
- src/events/GuildMemberRemove.ts
- src/events/GuildMemberUpdate.ts
Reverts Sachin-dot-py/r-igcse-bot#109
> Revert "feat: mention user"

- src/commands/moderation/RefreshHelpers.ts
- src/events/GuildMemberUpdate.ts
Automated refreshHelpers
+ fixed a bug in /refreshHelpers
> Automate Refresh Helpers

- .env.example
- global.d.ts
- src/events/ClientReady.ts
In this feature there's an embed sent to the main guild's channel configured in the env.
An example is given below
> Feat reminder hours

- src/commands/configuration/Setup.ts
- src/commands/moderation/Warn.ts
- src/commands/moderation/timeout/Timeout.ts
Reverts Sachin-dot-py/r-igcse-bot#130
> Revert "Modified & Created a new version of Action Required"

- src/commands/study/ChemInfo.ts
- src/data.ts
- src/utils/apis/cheminfo.ts
Added the cheminfo command and its API interface
> Add cheminfo command

- src/commands/configuration/OldPinsThread.ts
- src/commands/menus/TogglePin.ts
- src/mongo/schemas/OldPinsThread.ts
- Consider archived "Old pins" threads when pinning
- Add an option to manually mention Old Pins threads via a new /old_pins_thread command
> Old Pins Fix

- src/commands/study/Keyword.ts
- Limited to 25 autocomplete choices so discord actually shows
- Update title casing for embeds
> Quick fixes for autocomplete and embed

- src/commands/configuration/KeywordControl.ts
- src/commands/study/Keyword.ts
- src/data.ts
- src/events/InteractionCreate.ts
- src/mongo/schemas/GuildPreferences.ts
- Fix casing of keyword names
- Fix resource tag channel setup
- Change keyword embed colours
> Fix keyword system and resource tag channel

- src/commands/moderation/Warn.ts
- src/commands/moderation/timeout/Timeout.ts
- fix `totalPoints` not including current punishment's points
- FIXED THE DAMN SPACE LOOKED SO IRRITATING
> fix: include current points

- src/commands/moderation/Warn.ts
- src/commands/moderation/timeout/Timeout.ts
- fixed the extra point being added when showing points for `/warn`
- made some style changes
> fix: extra point for warn

- src/commands/miscellaneous/ModPing.ts
- src/redis/schemas/ModPing.ts
- fixed pinging for every previous user when the command was used
- refactored a bit
- no abusing !!!! (throws an error that doesnt affect user tho)
> fix: /mod_ping pinging multiple times

- src/commands/configuration/FeedbackChannel.ts
- src/commands/configuration/KeywordControl.ts
- src/commands/configuration/OldPinsThread.ts
- src/commands/configuration/ReactionRoles.ts
- src/commands/configuration/StudyChannel.ts
Imported MessageFlags following #193
> Ephemeral flags fix

- src/commands/moderation/History.ts
- src/commands/moderation/Note.ts
Features:
- Layout restructured
- Moderation notes added (Separate Embed).
- Mod usernames shown by default.
Could use a switch statement for the different infractions, originally wrote using ifs but not sure which is better in TS.
> Rewrote history command in order to have better visibility.

- src/commands/moderation/History.ts
- src/commands/moderation/Note.ts
Reverts Sachin-dot-py/r-igcse-bot#217
> Revert "Rewrote history command in order to have better visibility."

- src/commands/moderation/Lockdown.ts
- src/events/ClientReady.ts
- src/mongo/schemas/ChannelLockdown.ts
Adds a `/lockdown list` subcommand and enhances the scheduling system to support multiple lockdowns per channel. Improves overlap detection, batch handling, and database schema for more reliable and flexible lockdown management.
> feat(lockdown): add list subcommand and improve scheduling logic
